export type CategorySeed = {
  name: string;
  children?: CategorySeed[];
};

export const branchZoneSeeds = [
  'Dhaka',
  'Chattogram',
  'Rajshahi',
  'Khulna',
  'Barishal',
  'Mymensingh',
  'Bogura',
  'Rangpur',
  'Jashore',
  'Dinajpur',
  'Sylhet',
  'Kushtia',
  'eCommerce - Ready Stock',
];

export const pcBuilderComponentSeeds = [
  { name: 'CPU', slug: 'cpu', isRequired: true },
  { name: 'Motherboard', slug: 'motherboard', isRequired: true },
  { name: 'RAM', slug: 'ram', isRequired: true },
  { name: 'SSD', slug: 'ssd', isRequired: false },
  { name: 'HDD', slug: 'hdd', isRequired: false },
  { name: 'Casing', slug: 'casing', isRequired: true },
  { name: 'Keyboard', slug: 'keyboard', isRequired: false },
  { name: 'Mouse', slug: 'mouse', isRequired: false },
  { name: 'Monitor', slug: 'monitor', isRequired: false },
  { name: 'CPU Cooler', slug: 'cpu-cooler', isRequired: false },
  { name: 'Graphics Card', slug: 'graphics-card', isRequired: false },
  { name: 'Power Supply', slug: 'power-supply', isRequired: true },
  { name: 'Casing Fan', slug: 'casing-fan', isRequired: false, allowMultiple: true },
  { name: 'UPS', slug: 'ups', isRequired: false },
  { name: 'Optical Device', slug: 'optical-device', isRequired: false },
  { name: 'Accessories', slug: 'accessories', isRequired: false, allowMultiple: true },
  { name: 'Other Component', slug: 'other-component', isRequired: false, allowMultiple: true },
];

export const ccBuilderComponentSeeds = [
  { name: 'Camera', slug: 'camera', isRequired: true, allowMultiple: true },
  { name: 'Video Recorder (DVR/NVR)', slug: 'recorder', isRequired: true },
  { name: 'Storage', slug: 'storage', isRequired: true },
  { name: 'Power Source', slug: 'power-source', isRequired: true },
  { name: 'Connector', slug: 'connector', isRequired: false, allowMultiple: true },
  { name: 'Cable', slug: 'cable', isRequired: true },
  { name: 'Display', slug: 'display', isRequired: false },
  { name: 'Keyboard', slug: 'keyboard', isRequired: false },
  { name: 'Router', slug: 'router', isRequired: false },
  { name: 'Other Component', slug: 'other-component', isRequired: false, allowMultiple: true },
];

export const categorySeeds: CategorySeed[] = [
  {
    name: 'Laptop',
    children: [
      { name: 'All Laptop' },
      { name: 'Acer' },
      { name: 'Apple' },
      { name: 'ASUS' },
      { name: 'CHUWI' },
      { name: 'Dell' },
      { name: 'Gigabyte' },
      { name: 'HP' },
      { name: 'Lenovo' },
      { name: 'Microsoft' },
      { name: 'MSI' },
      { name: 'Smart' },
      { name: 'TECNO' },
      {
        name: 'Accessories',
        children: [
          { name: 'Laptop Ram' },
          { name: 'Laptop Cooler' },
          { name: 'Caddy' },
          { name: 'Laptop Bag' },
          { name: 'Stand' },
          { name: 'Battery' },
          { name: 'Adapter' },
        ],
      },
    ],
  },
  {
    name: 'Desktop and Server',
    children: [
      {
        name: 'Desktop PC',
        children: [
          { name: 'Brand Desktop PC' },
          { name: 'All In One PC' },
          { name: 'Mini PC' },
          { name: 'Ryans PC' },
          { name: 'AI Workstation PC' },
        ],
      },
      {
        name: 'Desktop Component',
        children: [
          { name: 'Processor' },
          { name: 'Motherboard' },
          { name: 'Desktop Ram' },
          { name: 'Optical Device' },
          { name: 'Graphics Card' },
          { name: 'Power Supply' },
          { name: 'Casing' },
          { name: 'Casing Fan' },
          { name: 'CPU Cooler' },
          { name: 'Keyboard' },
          { name: 'Mouse' },
          { name: 'Keyboard and Mouse Combo' },
          { name: 'Mouse Pad' },
          { name: 'Power Station' },
          { name: 'UPS' },
          { name: 'UPS Battery' },
        ],
      },
      {
        name: 'Server',
        children: [
          { name: 'Rack Server' },
          { name: 'Tower Server' },
          { name: 'June Server' },
        ],
      },
      {
        name: 'Server Component',
        children: [
          { name: 'Server Processor' },
          { name: 'Server Motherboard' },
          { name: 'Server Cabinet' },
        ],
      },
      {
        name: 'Desktop Accessories',
        children: [
          { name: 'LED Strip' },
          { name: 'Casing Accessories' },
          { name: 'Graphics Card Holder' },
          { name: 'Thermal Paste' },
        ],
      },
      {
        name: 'Storage',
        children: [
          { name: 'Internal HDD' },
          { name: 'Internal SSD' },
          { name: 'External HDD' },
          { name: 'External SSD' },
          { name: 'Pen Drive' },
          { name: 'Memory Card' },
          { name: 'HDD and SSD Case' },
          { name: 'Card Reader' },
        ],
      },
    ],
  },
  {
    name: 'Gaming',
    children: [
      {
        name: 'Gaming Component',
        children: [
          { name: 'Gaming Console' },
          { name: 'Gaming Controller' },
          { name: 'Virtual Reality VR' },
        ],
      },
      { name: 'Game Streaming' },
      { name: 'Games' },
      { name: 'Gaming Chair' },
      { name: 'Gaming Desk' },
      { name: 'Gaming Sofa' },
      { name: 'Gaming Component Accessories' },
      { name: 'Gaming Laptop' },
      { name: 'Gaming Desktop PC' },
      {
        name: 'Gaming Desktop Component',
        children: [
          { name: 'Motherboard' },
          { name: 'Desktop Ram' },
          { name: 'Graphics Card' },
          { name: 'Power Supply' },
          { name: 'Casing' },
          { name: 'CPU Cooler' },
          { name: 'Keyboard' },
          { name: 'Mouse' },
          { name: 'Keyboard and Mouse Combo' },
          { name: 'Mouse Pad' },
          { name: 'LED Strip' },
        ],
      },
      { name: 'Gaming Monitor' },
      {
        name: 'Sound System',
        children: [
          { name: 'Speaker' },
          { name: 'Headphone' },
          { name: 'Microphone' },
          { name: 'Earphone' },
        ],
      },
      { name: 'Gaming Network Router' },
    ],
  },
  {
    name: 'Monitor',
    children: [
      { name: 'All Monitor' },
      { name: 'Acer' },
      { name: 'AOC' },
      { name: 'Apple' },
      { name: 'Arzopa' },
      { name: 'ASUS' },
      { name: 'BenQ' },
      { name: 'Dahua' },
      { name: 'Dell' },
      { name: 'Gigabyte' },
      { name: 'Hikvision' },
      { name: 'HP' },
      { name: 'Lenovo' },
      { name: 'LG' },
      { name: 'MSI' },
      { name: 'PC Power' },
      { name: 'Philips' },
      { name: 'Samsung' },
      { name: 'Value Top' },
      { name: 'ViewSonic' },
      { name: 'Xiaomi' },
      {
        name: 'Monitor Accessories',
        children: [{ name: 'Monitor Mounts and Brackets' }],
      },
    ],
  },
  {
    name: 'Tablet PC',
    children: [
      {
        name: 'Regular Tablet PC',
        children: [
          { name: 'Amazon' },
          { name: 'CHUWI' },
          { name: 'HONOR' },
          { name: 'Lenovo' },
          { name: 'Samsung' },
          { name: 'Teclast' },
          { name: 'Xiaomi' },
        ],
      },
      { name: 'Kids Tablet PC', children: [{ name: 'Teclast' }] },
      {
        name: 'Graphics Tablet PC',
        children: [
          { name: 'Huion' },
          { name: 'Wacom' },
          { name: 'XP-Pen' },
        ],
      },
      { name: 'Apple Tablet PC', children: [{ name: 'iPad' }] },
      { name: 'Digital Signature Pad' },
      { name: 'Stylus Pen' },
      {
        name: 'Tablet PC Accessories',
        children: [
          { name: 'Power Bank' },
          { name: 'Car Charger' },
          { name: 'Wireless Charger' },
          { name: 'Wall Charger' },
          { name: 'Cable Organizer' },
          { name: 'Phone Holder' },
          { name: 'Selfie Stick' },
          { name: 'Screen Cleaner' },
          { name: 'Tablet PC Case' },
        ],
      },
    ],
  },
  {
    name: 'Printer',
    children: [
      {
        name: 'Document Printer',
        children: [
          { name: 'Laser Printer' },
          { name: 'Ink Printer' },
          { name: 'Dot Matrix Printer' },
          { name: 'Label Printer' },
        ],
      },
      { name: 'Card Printer' },
      { name: 'POS Printer' },
      { name: 'Large Format Printer' },
      { name: 'Printer Paper' },
      {
        name: 'Consumable',
        children: [
          { name: 'Toner' },
          { name: 'Cartridge' },
          { name: 'Ribbon' },
          { name: 'Refill' },
          { name: 'Drum Unit' },
          { name: 'Print Head' },
          { name: 'Accessories' },
        ],
      },
    ],
  },
  {
    name: 'Camera',
    children: [
      {
        name: 'Digital SLR Camera',
        children: [
          { name: 'DSLR Camera' },
          { name: 'Mirrorless Camera' },
          { name: 'DSLR Camera Accessories' },
          { name: 'DSLR Camera Lens' },
        ],
      },
      { name: 'Digital Compact Camera' },
      { name: 'Compact Camera' },
      { name: 'Action Camera' },
      { name: 'Compact Camera Accessories' },
      { name: 'Video Camera' },
      { name: 'Video Conferencing' },
      { name: 'Webcam' },
      { name: 'Drone' },
      { name: 'Drone Accessories' },
      { name: 'Gimbal' },
      {
        name: 'Studio Equipments',
        children: [
          { name: 'Tripod' },
          { name: 'Umbrella' },
          { name: 'Flash and Ring Light' },
          { name: 'Mixer' },
          { name: 'Studio Headphone' },
          { name: 'Studio Microphone' },
          { name: 'Audio Interface' },
        ],
      },
    ],
  },
  {
    name: 'Security',
    children: [
      { name: 'CC Camera' },
      { name: 'IP Camera' },
      { name: 'Wireless / Wi-Fi Camera' },
      { name: 'DVR' },
      { name: 'NVR' },
      { name: 'XVR' },
      { name: 'CC/IP Camera Accessories' },
      { name: 'CCTV Package' },
      {
        name: 'Home Security',
        children: [
          { name: 'Smart Lock' },
          { name: 'Smart Door Bell' },
          { name: 'Entrance Control' },
        ],
      },
      {
        name: 'Time Attendance System',
        children: [
          { name: 'Access Control' },
          { name: 'Access Control Accessories' },
          { name: 'Access Control Software' },
        ],
      },
    ],
  },
  {
    name: 'Network',
    children: [
      {
        name: 'Satellite Internet',
        children: [
          { name: 'STARLINK' },
          { name: 'STARLINK Accessories' },
        ],
      },
      { name: 'Network Router' },
      { name: 'Access Point' },
      { name: 'Range Extender' },
      { name: 'Network Switch' },
      { name: 'Lan Card' },
      { name: 'Wifi Adapter' },
      { name: 'Network Cable' },
      { name: 'Optical Line Termination OLT' },
      { name: 'Optical Network Unit ONU' },
      { name: 'Network Storage' },
      { name: 'Edge Modem' },
      { name: 'Splicer Machine' },
      {
        name: 'Network Accessories',
        children: [
          { name: 'Connector' },
          { name: 'Face Plate' },
          { name: 'Cable Lan' },
          { name: 'Crimping Tool' },
          { name: 'Management Cable' },
          { name: 'Patch Panel' },
          { name: 'Modular' },
          { name: 'Extender' },
        ],
      },
    ],
  },
  {
    name: 'Sound',
    children: [
      { name: 'Speaker' },
      { name: 'Home Theater Systems' },
      { name: 'PA System' },
      { name: 'Amplifier' },
      { name: 'Headphone' },
      { name: 'Earphone' },
      { name: 'Earbuds' },
      { name: 'Neckband' },
      { name: 'Music Player' },
      { name: 'Microphone' },
      { name: 'Voice Recorder' },
      { name: 'Radio' },
      { name: 'Musical Instrument' },
      { name: 'Sound System Accessories' },
      { name: 'Megaphone' },
    ],
  },
  {
    name: 'Office Items',
    children: [
      { name: 'Photocopier' },
      { name: 'Photocopier Accessories' },
      {
        name: 'Scanner',
        children: [
          { name: 'Flatbed Scanner' },
          { name: 'Sheeted and Flatbed Scanner' },
          { name: 'Document and Book Scanner' },
          { name: 'Cheque Scanner' },
          { name: 'Large Format Scanner' },
        ],
      },
      { name: 'Projector' },
      { name: 'Projector Screen' },
      { name: 'Projector Accessories' },
      { name: 'Ceiling Mount kit' },
      { name: 'Presenter' },
      { name: 'Conference System' },
      {
        name: 'Digital Display',
        children: [
          { name: 'Interactive Panel' },
          { name: 'Digital Signage' },
          { name: 'Digital Kiosk' },
          { name: 'Video Wall' },
          { name: 'Commercial Display' },
          { name: 'OPS' },
          { name: 'Digital Display Accessories' },
        ],
      },
      {
        name: 'POS System',
        children: [
          { name: 'POS Terminals' },
          { name: 'POS Printers' },
          { name: 'Label Printers' },
          { name: 'Barcode and QR Scanner' },
          { name: 'Weighing Scale' },
          { name: 'Cash Register Machine and Drawer' },
          { name: 'POS and Label Supplies' },
          { name: 'POS Accessories' },
        ],
      },
      {
        name: 'Telephone Set',
        children: [
          { name: 'Land Phone Set' },
          { name: 'IP Phone Set' },
          { name: 'Fax Machine' },
          { name: 'Telephone & Fax Accessories' },
        ],
      },
      { name: 'Money Counting Machine' },
      { name: 'Laminating and Binding Machine' },
      { name: 'Paper Shredder' },
      { name: 'Safe Box / Locker / Vault' },
      { name: 'Office Accessories' },
      { name: 'Power Station' },
      { name: 'Calculator' },
      { name: 'Intercom Packages' },
    ],
  },
  {
    name: 'Accessories',
    children: [
      { name: 'Cable / Converter / HUB', children: [{ name: 'Bluetooth Adapter' }] },
      {
        name: 'Electrical Power',
        children: [
          { name: 'Power Strip' },
          { name: 'DryCell Battery' },
          { name: 'Blower' },
          { name: 'Power Cable' },
          { name: 'Socket' },
          { name: 'Mini UPS' },
          { name: 'Power Station' },
          { name: 'Solar Panel' },
        ],
      },
      { name: 'Signature Pad' },
      { name: 'Digital Pen' },
      {
        name: 'Tablet Accessories',
        children: [
          { name: 'Power Bank' },
          { name: 'Car Charger' },
          { name: 'Wireless Charger' },
          { name: 'Wall Charger' },
        ],
      },
      { name: 'Cable Organizer' },
      { name: 'Phone Holder' },
      { name: 'Selfie Stick' },
      { name: 'Screen Cleaner' },
      { name: 'Tablet PC Case' },
      { name: 'Bag' },
    ],
  },
];
